/**
 * 错误码常量定义
 *
 * @description 错误处理相关的常量定义
 */

/**
 * 错误码常量
 */
export const ERROR_CODES = {
  // 通用错误
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_PARAMETER: 'INVALID_PARAMETER',
  UNSUPPORTED_OPERATION: 'UNSUPPORTED_OPERATION',

  // 密钥相关错误
  INVALID_KEY: 'INVALID_KEY',
  INVALID_KEY_FORMAT: 'INVALID_KEY_FORMAT',
  KEY_GENERATION_FAILED: 'KEY_GENERATION_FAILED',

  // 算法相关错误
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  INVALID_CIPHERTEXT: 'INVALID_CIPHERTEXT',
  ENCRYPTION_FAILED: 'ENCRYPTION_FAILED',
  DECRYPTION_FAILED: 'DECRYPTION_FAILED',

  // 运行时错误
  RUNTIME_NOT_SUPPORTED: 'RUNTIME_NOT_SUPPORTED',
  FEATURE_NOT_AVAILABLE: 'FEATURE_NOT_AVAILABLE',
} as const;
